In [1]:
import sys
import pandas as pd
from pathlib import Path
pd.set_option('display.max_columns', None)
sys.path.append(str(Path.cwd().parent / "src"))
import csv
import numpy
import utils.data_loader as dl
import utils.data_summaries as ds
import utils.standardize_columns as sc

In [2]:
#print(dir(dl))
#print(dir(ds))
print(dir(sc))

['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_resolve', 'col_to_bool', 'col_to_cat', 'col_to_date', 'col_to_float', 'col_to_int', 'col_to_snake', 'col_to_str', 'pd', 're']

In [3]:
#Read available datasets available for data source
path = "C:\\Users\\1\\Desktop\\project\\data\\cleaned_data"
DataSources = dl.get_sources(path)
print(DataSources)

[WindowsPath('C:/Users/1/Desktop/project/data/cleaned_data/311'), WindowsPath('C:/Users/1/Desktop/project/data/cleaned_data/climate'), WindowsPath('C:/Users/1/Desktop/project/data/cleaned_data/neighbourhoods'), WindowsPath('C:/Users/1/Desktop/project/data/cleaned_data/ward_census'), WindowsPath('C:/Users/1/Desktop/project/data/cleaned_data/watermain_breaks'), WindowsPath('C:/Users/1/Desktop/project/data/cleaned_data/watermains'), WindowsPath('C:/Users/1/Desktop/project/data/cleaned_data/weather')]

In [4]:
source = DataSources[1]
readable = dl.read_files(source)
readable

CSV
  climate_variables_clean.csv

[WindowsPath('C:/Users/1/Desktop/project/data/cleaned_data/climate/climate_variables_clean.csv')]

In [5]:
data = dl.pull_data(source)
print(f"number of datasets from source: {len(data)}")
print(f"names of remaining datasets: {data.keys()}")

CSV
  climate_variables_clean.csv
number of datasets from source: 1
names of remaining datasets: dict_keys(['climate_variables_clean'])

In [6]:
climate = data['climate_variables_clean']
ds.quick_summary(climate) ##many columns have the same number of missing %, we should check which rows have null

,dtype,col_index,missing_pct,n_unique
id,int64,0,0.000000,27
climate_scenario,object,1,0.000000,3
time_horizon,object,2,0.074074,4
distribution,object,3,0.000000,4
annual_mean_temperature,float64,4,0.074074,18
winter_mean_temperature,float64,5,0.074074,19
spring_mean_temperature,float64,6,0.074074,18
summer_mean_temperature,float64,7,0.074074,19
fall_mean_temperature,float64,8,0.074074,19
annual_maximum_temperature,float64,9,0.074074,18
winter_maximum_temperature,float64,10,0.074074,16
spring_maximum_temperature,float64,11,0.074074,17
summer_maximum_temperature,float64,12,0.074074,18
fall_maximum_temperature,float64,13,0.074074,18
annual_minimum_temperature,float64,14,0.074074,19
winter_minimum_temperature,float64,15,0.074074,18
spring_minimum_temperature,float64,16,0.074074,19
summer_minimum_temperature,float64,17,0.074074,18
fall_minimum_temperature,float64,18,0.074074,18
days_above_35_c,float64,19,0.074074,16
days_above_30_c,float64,20,0.074074,21
days_above_25_c,float64,21,0.074074,22
days_above_20_c_tropical_nights,float64,22,0.074074,22
hottest_day_temperature,float64,23,0.074074,20
temperature_based_heat_warning_frequency,float64,24,0.074074,19
maximum_consecutive_temperature_based_heat_warning_days,float64,25,0.074074,23
humidex_above_30,float64,26,0.111111,22
humidex_above_35,float64,27,0.111111,21
humidex_above_40,float64,28,0.111111,20
days_below_minus_20_c,float64,29,0.074074,9
days_below_minus_10_c,float64,30,0.074074,22
days_below_0_c_frost_days,float64,31,0.074074,22
heating_degree_days,float64,32,0.074074,25
cooling_degree_days,float64,33,0.074074,25
annual_total_precipitation,float64,34,0.074074,22
winter_total_precipitation,float64,35,0.074074,22
spring_total_precipitation,float64,36,0.074074,22
summer_total_precipitation,float64,37,0.074074,22
fall_total_precipitation,float64,38,0.074074,21
maximum_1_day_precipitation,float64,39,0.074074,22
maximum_3_day_precipitation,float64,40,0.074074,22
simple_daily_intensity_index,float64,41,0.074074,16
95_th_percentile_precipitation,float64,42,0.074074,18
99_th_percentile_precipitation,float64,43,0.074074,21
maximum_consecutive_wet_days,float64,44,0.074074,13
annual_total_dry_days,float64,45,0.074074,21
maximum_consecutive_dry_days,float64,46,0.074074,19
frost_free_season_start_date,object,47,0.000000,18
frost_free_season_end_date,object,48,0.000000,20
frost_free_season_length,float64,49,0.074074,22
corn_heat_units,float64,50,0.074074,22
growing_degree_days_base_0_c,float64,51,0.074074,22
canola_growing_degree_days_base_4_c,float64,52,0.074074,22
forage_crops_growing_degree_days_base_5_c,float64,53,0.074074,22
corn_and_bean_growing_degree_days_base_10_c,float64,54,0.074074,22
growing_degree_days_base_15_c,float64,55,0.074074,22
freeze_thaw_cycles,float64,56,0.074074,21
freezing_rain_potential,float64,57,0.074074,18

In [7]:
climate

,id,climate_scenario,time_horizon,distribution,annual_mean_temperature,winter_mean_temperature,spring_mean_temperature,summer_mean_temperature,fall_mean_temperature,annual_maximum_temperature,winter_maximum_temperature,spring_maximum_temperature,summer_maximum_temperature,fall_maximum_temperature,annual_minimum_temperature,winter_minimum_temperature,spring_minimum_temperature,summer_minimum_temperature,fall_minimum_temperature,days_above_35_c,days_above_30_c,days_above_25_c,days_above_20_c_tropical_nights,hottest_day_temperature,temperature_based_heat_warning_frequency,maximum_consecutive_temperature_based_heat_warning_days,humidex_above_30,humidex_above_35,humidex_above_40,days_below_minus_20_c,days_below_minus_10_c,days_below_0_c_frost_days,heating_degree_days,cooling_degree_days,annual_total_precipitation,winter_total_precipitation,spring_total_precipitation,summer_total_precipitation,fall_total_precipitation,maximum_1_day_precipitation,maximum_3_day_precipitation,simple_daily_intensity_index,95_th_percentile_precipitation,99_th_percentile_precipitation,maximum_consecutive_wet_days,annual_total_dry_days,maximum_consecutive_dry_days,frost_free_season_start_date,frost_free_season_end_date,frost_free_season_length,corn_heat_units,growing_degree_days_base_0_c,canola_growing_degree_days_base_4_c,forage_crops_growing_degree_days_base_5_c,corn_and_bean_growing_degree_days_base_10_c,growing_degree_days_base_15_c,freeze_thaw_cycles,freezing_rain_potential
0,1,OBSERVED_TORONTO_AVERAGE,1971-2000,MEDIAN,7.9,-4.3,6.5,19.7,9.5,12.5,-0.4,11.3,25.1,13.8,3.4,-7.9,1.7,14.4,5.3,0.3,9.9,57.8,5.0,33.1,0.5,1.2,NaN,NaN,NaN,3.7,39.2,133.7,3933.9,256.7,753.4,156.8,189.3,197.6,208.3,37.3,50.2,4.9,11.2,21.9,8.0,211.0,13.4,05-Apr,19-Nov,233.0,3602.7,3426.4,2422.4,2200.5,1248.3,548.0,65.5,3.2
1,2,SSP2-4.5,1971-2000,10th_PERCENTILE,7.2,-6.3,4.9,18.9,8.7,11.7,-2.5,9.4,24.0,12.8,2.7,-10.1,0.4,13.7,4.5,0.0,3.5,43.1,1.7,31.3,0.0,0.0,28.7,3.3,0.0,0.2,21.6,113.7,3596.8,194.1,671.9,125.6,140.9,141.5,144.9,28.5,41.1,4.4,9.9,18.9,4.2,193.8,8.9,20-Mar,03-Nov,208.0,3376.7,3247.4,2273.4,2058.8,1138.1,464.9,49.8,0.4
2,3,SSP2-4.5,1971-2000,MEDIAN,8.1,-4.1,6.5,19.9,9.9,12.5,-0.5,11.2,25.1,14.1,3.6,-7.7,1.9,14.6,5.6,0.0,9.9,57.6,5.5,33.4,0.2,0.6,41.1,8.7,0.2,2.6,36.3,129.8,3887.6,269.9,795.1,171.3,199.0,204.0,207.6,37.4,55.2,5.1,11.9,22.8,5.4,207.2,11.9,05-Apr,18-Nov,230.0,3631.4,3465.0,2453.5,2231.0,1274.2,568.6,61.9,2.1
3,4,SSP2-4.5,1971-2000,90th_PERCENTILE,9.0,-1.9,8.2,21.0,11.2,13.5,1.5,13.2,26.5,15.5,4.6,-5.2,3.4,15.6,6.9,1.1,20.1,72.1,11.9,35.5,2.2,4.8,52.9,17.4,2.0,7.4,51.4,145.1,4173.5,357.5,919.3,227.0,265.3,277.5,286.4,60.8,80.6,5.7,13.8,27.7,7.1,220.1,16.9,16-Apr,02-Dec,268.0,3927.1,3706.6,2658.5,2425.5,1421.3,680.2,74.5,4.4
4,5,SSP2-4.5,2015-2040,10th_PERCENTILE,9.1,-3.8,6.8,20.6,10.5,13.4,-0.4,11.3,25.7,14.6,4.7,-7.3,2.2,15.4,6.2,0.0,11.5,66.0,7.4,33.0,0.2,0.5,49.4,11.0,0.2,0.0,7.5,87.5,3010.0,333.5,700.6,139.6,149.2,140.4,148.8,29.4,42.9,4.6,10.4,19.7,4.4,193.2,9.1,07-Mar,13-Nov,227.2,3907.2,3716.1,2658.3,2423.9,1417.4,663.3,41.9,0.4
5,6,SSP2-4.5,2015-2040,MEDIAN,10.1,-1.7,8.4,21.7,11.8,14.5,1.5,13.2,27.1,16.1,5.6,-5.0,3.7,16.3,7.4,1.1,23.9,83.1,15.0,35.4,1.8,5.1,63.1,22.1,2.0,0.2,18.7,106.5,3324.2,441.2,832.8,188.0,212.1,208.7,213.1,40.4,58.2,5.3,12.3,24.1,5.6,207.5,12.0,24-Mar,26-Nov,260.2,4250.4,3995.4,2899.8,2656.7,1600.0,798.0,54.5,2.3
6,7,SSP2-4.5,2015-2040,90th_PERCENTILE,11.2,0.3,10.2,23.0,13.3,15.7,3.3,15.2,28.7,18.0,6.7,-2.7,5.2,17.4,8.9,6.5,40.2,101.0,26.5,38.2,4.3,14.2,78.5,34.2,6.8,2.6,32.9,124.9,3629.2,582.6,989.5,256.0,282.9,293.9,294.8,63.0,86.7,6.2,14.8,29.6,7.6,220.3,16.8,08-Apr,14-Dec,314.9,4590.2,4293.9,3173.4,2923.7,1821.9,972.3,68.1,5.3
7,8,SSP2-4.5,2041-2070,10th_PERCENTILE,10.1,-2.7,7.8,21.5,11.4,14.4,0.6,12.2,26.6,15.6,5.7,-6.0,3.3,16.3,7.1,0.2,18.9,77.9,14.0,34.1,1.5,3.9,62.0,19.6,1.1,0.0,2.2,68.5,2618.5,441.3,733.9,140.5,158.9,138.3,152.1,31.8,46.6,4.8,10.7,20.8,4.4,192.5,9.0,28-Feb,16-Nov,243.0,4222.0,3994.1,2897.2,2650.1,1583.6,780.7,35.0,0.6
8,9,SSP2-4.5,2041-2070,MEDIAN,11.3,-0.4,9.5,22.9,12.8,15.7,2.6,14.3,28.3,17.2,6.8,-3.3,4.7,17.4,8.4,3.3,36.2,97.1,26.0,36.6,4.2,14.1,79.0,36.7,6.7,0.0,11.5,92.3,2939.9,615.9,871.5,198.9,224.5,212.0,225.3,42.4,62.4,5.5,12.9,25.2,5.6,207.4,12.1,March 19,01-Dec,290.0,4597.3,4325.1,3177.6,2922.1,1812.4,961.4,49.5,2.8
9,10,SSP2-4.5,2041-2070,90th_PERCENTILE,12.5,1.7,11.2,24.4,14.5,17.0,4.6,16.3,30.2,19.1,8.0,-1.1,6.1,18.7,10.1,13.2,58.5,116.2,40.3,39.4,7.2,28.4,97.0,55.1,15.8,0.9,24.6,113.1,3323.7,780.2,1021.9,268.0,298.5,301.9,306.9,67.8,92.2,6.3,15.5,31.2,7.6,220.1,17.2,06-Apr,18-Dec,340.0,4963.5,4662.8,3477.7,3215.1,2075.9,1175.8,63.7,6.5
10,11,SSP2-4.5,2071-2100,10th_PERCENTILE,10.9,-1.5,8.5,22.2,12.1,15.2,1.6,13.0,27.4,16.3,6.6,-4.7,4.0,17.0,7.8,0.5,26.6,87.6,20.7,34.9,2.3,7.4,71.5,29.1,2.9,0.0,0.2,47.9,2332.0,530.1,737.4,146.9,158.0,140.0,150.9,32.6,47.3,4.9,10.8,21.3,4.4,192.9,9.3,19-Feb,19-Nov,257.0,4436.1,4206.0,3068.1,2811.9,1714.2,886.6,26.5,0.7
11,12,SSP2-4.5,2071-2100,MEDIAN,12.1,0.9,10.4,23.8,13.7,16.6,3.8,15.1,29.2,18.0,7.7,-2.0,5.5,18.3,9.3,5.6,46.2,107.6,35.5,37.4,5.1,22.0,91.4,49.3,12.3,0.0,5.9,79.7,2723.1,729.2,885.4,208.8,230.7,207.9,220.0,44.1,63.5,5.6,13.2,25.7,5.7,207.1,12.2,15-Mar,05-Dec,314.0,4876.6,4586.1,3408.3,3145.0,1991.1,1091.5,44.9,3.1
12,13,SSP2-4.5,2071-2100,90th_PERCENTILE,13.8,3.3,12.2,25.7,15.7,18.4,6.0,17.3,31.6,20.4,9.3,0.6,7.2,19.8,11.2,21.2,73.2,127.7,54.3,40.9,8.0,39.6,109.5,70.5,25.1,0.2,16.8,102.8,3088.2,923.0,1041.3,275.3,309.4,299.1,313.6,70.2,95.4,6.5,15.7,32.2,7.6,221.6,17.3,02-Apr,20-Dec,355.0,5354.3,5070.0,3803.0,3525.1,2326.1,1368.8,60.1,7.5
13,14,SSP2-4.5,NaN,OVERALL_TREND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,up,up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,SSP5-8.5,1971-2000,10th_PERCENTILE,7.2,-6.3,4.9,18.9,8.7,11.7,-2.5,9.4,24.0,12.8,2.7,-10.1,0.4,13.7,4.5,0.0,3.5,43.1,1.7,31.3,0.0,0.0,28.7,3.3,0.0,0.2,21.6,113.7,3595.2,193.7,671.9,125.6,140.9,141.5,144.9,28.5,41.1,4.4,9.9,18.9,4.2,193.8,8.9,20-Mar,03-Nov,208.0,3376.7,3247.4,2273.4,2058.8,1138.1,464.9,49.8,0.4
15,16,SSP5-8.5,1971-2000,MEDIAN,8.1,-4.1,6.5,19.9,9.9,12.5,-0.5,11.2,25.1,14.1,3.6,-7.7,1.9,14.6,5.6,0.0,9.9,57.6,5.5,33.4,0.2,0.6,41.1,8.9,0.2,2.6,36.3,129.8,3887.0,269.6,795.1,171.3,199.0,204.0,207.6,37.4,55.2,5.1,11.9,22.8,5.4,207.2,11.8,05-Apr,18-Nov,230.0,3631.4,3465.0,2453.5,2231.0,1274.2,568.6,61.9,2.1
16,17,SSP5-8.5,1971-2000,90th_PERCENTILE,9.0,-1.9,8.2,21.0,11.2,13.5,1.5,13.2,26.5,15.5,4.6,-5.2,3.4,15.6,6.9,1.1,20.1,72.1,11.9,35.5,2.2,4.7,52.8,17.4,2.1,7.4,51.4,145.1,4173.2,357.1,919.3,227.0,265.3,277.5,286.4,60.8,80.6,5.7,13.8,27.7,7.1,220.1,16.9,16-Apr,02-Dec,268.0,3927.1,3706.6,2658.5,2425.5,1421.3,680.2,74.5,4.4
17,18,SSP5-8.5,2015-2040,10th_PERCENTILE,9.1,-3.8,6.5,20.6,10.5,13.4,-0.4,11.0,25.7,14.6,4.7,-7.3,2.1,15.4,6.2,0.0,11.8,66.1,8.2,33.1,0.3,0.7,49.2,11.4,0.1,0.0,5.8,84.9,2972.5,334.0,712.7,137.2,150.0,139.8,148.3,30.1,44.4,4.6,10.4,20.1,4.3,194.4,9.0,07-Mar,12-Nov,230.2,3895.8,3717.5,2655.8,2421.0,1412.2,657.9,41.9,0.4
18,19,SSP5-8.5,2015-2040,MEDIAN,10.2,-1.4,8.4,21.7,11.8,14.6,1.8,13.1,27.1,16.1,5.8,-4.7,3.7,16.4,7.5,1.2,24.3,83.6,15.9,35.5,1.8,5.6,64.2,22.2,2.2,0.1,17.7,104.8,3295.6,446.5,840.4,191.2,211.0,211.1,212.4,41.4,59.5,5.3,12.4,24.4,5.7,207.3,12.1,25-Mar,25-Nov,264.3,4237.6,4005.1,2904.7,2661.1,1612.8,813.3,54.6,2.4
19,20,SSP5-8.5,2015-2040,90th_PERCENTILE,11.4,0.8,10.1,23.3,13.3,16.0,3.8,15.3,28.9,17.8,6.9,-2.2,5.1,17.7,8.9,8.0,43.8,104.6,28.5,38.5,4.6,16.2,81.4,36.7,7.1,2.3,32.1,122.6,3640.9,615.8,988.3,276.3,290.3,296.5,303.8,65.0,87.9,6.1,14.8,30.3,7.5,220.8,17.1,08-Apr,15-Dec,320.0,4618.2,4346.6,3216.0,2964.5,1868.3,1015.0,67.4,6.1
20,21,SSP5-8.5,2041-2070,10th_PERCENTILE,10.9,-1.6,8.5,22.2,12.0,15.2,1.5,13.0,27.3,16.2,6.6,-4.8,3.9,17.0,7.8,0.5,25.4,86.8,21.4,34.6,2.5,7.9,72.4,30.6,3.1,0.0,0.4,47.1,2330.6,521.3,730.6,148.1,161.3,138.1,150.9,31.9,47.0,4.9,10.8,20.9,4.3,193.5,9.2,20-Feb,19-Nov,258.0,4455.0,4224.9,3085.5,2829.0,1716.4,881.5,23.8,0.8
21,22,SSP5-8.5,2041-2070,MEDIAN,12.1,0.7,10.3,23.6,13.6,16.5,3.5,15.1,29.0,18.0,7.7,-2.2,5.5,18.2,9.2,5.5,44.3,106.1,34.7,37.2,5.3,23.1,89.3,47.5,12.1,0.0,6.5,80.5,2713.4,730.2,874.9,203.5,229.1,208.1,223.6,43.9,64.1,5.6,13.1,25.7,5.7,207.0,12.0,15-Mar,06-Dec,310.0,4844.1,4560.7,3383.4,3119.1,1958.3,1070.6,44.4,3.1
22,23,SSP5-8.5,2041-2070,90th_PERCENTILE,13.7,3.3,12.0,25.6,15.6,18.2,6.0,17.1,31.7,20.3,9.2,0.7,7.0,19.7,11.2,22.6,74.7,126.6,54.4,40.8,8.2,44.0,107.8,68.9,26.2,0.4,18.1,102.4,3119.6,955.7,1041.9,274.3,312.6,301.5,308.5,69.0,94.8,6.4,15.7,31.8,7.7,221.1,17.0,01-Apr,20-Dec,353.0,5315.6,5039.5,3793.5,3517.2,2316.4,1376.9,59.1,8.8
23,24,SSP5-8.5,2071-2100,10th_PERCENTILE,13.0,0.8,10.7,24.1,14.1,17.2,3.6,15.1,29.2,18.3,8.7,-2.2,6.1,18.9,9.8,5.4,48.5,107.1,42.5,36.8,4.6,25.7,94.1,55.2,17.5,0.0,0.0,11.6,1652.5,764.9,775.1,165.2,171.8,131.5,155.3,33.9,50.6,5.1,11.5,22.3,4.4,193.6,9.3,02-Feb,27-Nov,296.0,5071.8,4824.7,3578.4,3297.3,2083.4,1159.9,5.3,0.1
24,25,SSP5-8.5,2071-2100,MEDIAN,14.6,3.2,12.5,26.4,16.2,18.9,5.9,17.4,31.8,20.6,10.2,0.5,7.7,20.9,11.7,22.6,77.9,130.6,69.7,40.0,7.0,60.4,116.9,80.5,39.5,0.0,0.7,47.5,2142.4,1154.9,921.4,224.5,243.8,205.5,229.8,47.5,69.4,5.9,13.9,27.4,5.8,207.9,12.3,27-Feb,13-Dec,347.0,5660.8,5372.1,4086.8,3795.8,2519.7,1514.0,29.3,2.3
25,26,SSP5-8.5,2071-2100,90th_PERCENTILE,16.8,5.8,14.7,29.0,19.1,21.3,8.2,19.8,35.2,23.8,12.4,3.6,9.8,22.9,14.6,58.1,112.3,157.8,98.3,44.4,9.8,88.5,140.4,108.5,72.0,0.0,6.3,77.4,2561.8,1488.5,1101.0,303.9,336.2,297.4,329.6,74.1,104.1,6.8,16.8,34.2,7.8,222.3,17.6,20-Mar,23-Dec,364.0,6295.9,6110.6,4737.3,4422.2,3072.1,1984.7,48.5,7.9
26,27,SSP5-8.5,NaN,OVERALL_TREND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,up,up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
climate[climate.isna().any(axis=1)] ##only 3 rows, with missing values, a median and overall trend, we can drop this as we are predicting
climate1 = climate.dropna() #drop those 3 rows
climate1 = climate1.reset_index(drop=True)
#drop id column
climate2 = climate1.drop(columns=climate1.columns[0])
ds.quick_summary(climate2) ##many columns have the same number of missing %, we should check which rows have null

,dtype,col_index,missing_pct,n_unique
climate_scenario,object,0,0.0,2
time_horizon,object,1,0.0,4
distribution,object,2,0.0,3
annual_mean_temperature,float64,3,0.0,17
winter_mean_temperature,float64,4,0.0,18
spring_mean_temperature,float64,5,0.0,18
summer_mean_temperature,float64,6,0.0,18
fall_mean_temperature,float64,7,0.0,18
annual_maximum_temperature,float64,8,0.0,18
winter_maximum_temperature,float64,9,0.0,16
spring_maximum_temperature,float64,10,0.0,17
summer_maximum_temperature,float64,11,0.0,18
fall_maximum_temperature,float64,12,0.0,17
annual_minimum_temperature,float64,13,0.0,18
winter_minimum_temperature,float64,14,0.0,17
spring_minimum_temperature,float64,15,0.0,18
summer_minimum_temperature,float64,16,0.0,17
fall_minimum_temperature,float64,17,0.0,17
days_above_35_c,float64,18,0.0,15
days_above_30_c,float64,19,0.0,21
days_above_25_c,float64,20,0.0,21
days_above_20_c_tropical_nights,float64,21,0.0,21
hottest_day_temperature,float64,22,0.0,20
temperature_based_heat_warning_frequency,float64,23,0.0,18
maximum_consecutive_temperature_based_heat_warning_days,float64,24,0.0,22
humidex_above_30,float64,25,0.0,22
humidex_above_35,float64,26,0.0,21
humidex_above_40,float64,27,0.0,20
days_below_minus_20_c,float64,28,0.0,8
days_below_minus_10_c,float64,29,0.0,21
days_below_0_c_frost_days,float64,30,0.0,21
heating_degree_days,float64,31,0.0,24
cooling_degree_days,float64,32,0.0,24
annual_total_precipitation,float64,33,0.0,21
winter_total_precipitation,float64,34,0.0,21
spring_total_precipitation,float64,35,0.0,21
summer_total_precipitation,float64,36,0.0,21
fall_total_precipitation,float64,37,0.0,20
maximum_1_day_precipitation,float64,38,0.0,21
maximum_3_day_precipitation,float64,39,0.0,21
simple_daily_intensity_index,float64,40,0.0,16
95_th_percentile_precipitation,float64,41,0.0,17
99_th_percentile_precipitation,float64,42,0.0,20
maximum_consecutive_wet_days,float64,43,0.0,12
annual_total_dry_days,float64,44,0.0,20
maximum_consecutive_dry_days,float64,45,0.0,18
frost_free_season_start_date,object,46,0.0,17
frost_free_season_end_date,object,47,0.0,19
frost_free_season_length,float64,48,0.0,21
corn_heat_units,float64,49,0.0,21
growing_degree_days_base_0_c,float64,50,0.0,21
canola_growing_degree_days_base_4_c,float64,51,0.0,21
forage_crops_growing_degree_days_base_5_c,float64,52,0.0,21
corn_and_bean_growing_degree_days_base_10_c,float64,53,0.0,21
growing_degree_days_base_15_c,float64,54,0.0,21
freeze_thaw_cycles,float64,55,0.0,20
freezing_rain_potential,float64,56,0.0,17

In [9]:
ds.quick_summary(climate1) # no more missing values, many columns though, will have to decide whats needed..
#we will remove all the hot weather flags, I believe hot weather has negligible impact on flooding and water infrastructure health
climate_heatless = climate2.drop(columns=climate2.columns[18:30]) 
#remove trend days
climate_heatless1 = climate_heatless.drop(columns=climate_heatless.columns[19:21])
#next we cut out dry days
climate_dryless = climate_heatless1.drop(columns=climate_heatless1.columns[30:41])
ds.quick_summary(climate_dryless)
#drop freezing rain
climate_humid = climate_dryless.drop(columns='freezing_rain_potential')
climate_humid

,climate_scenario,time_horizon,distribution,annual_mean_temperature,winter_mean_temperature,spring_mean_temperature,summer_mean_temperature,fall_mean_temperature,annual_maximum_temperature,winter_maximum_temperature,spring_maximum_temperature,summer_maximum_temperature,fall_maximum_temperature,annual_minimum_temperature,winter_minimum_temperature,spring_minimum_temperature,summer_minimum_temperature,fall_minimum_temperature,days_below_0_c_frost_days,annual_total_precipitation,winter_total_precipitation,spring_total_precipitation,summer_total_precipitation,fall_total_precipitation,maximum_1_day_precipitation,maximum_3_day_precipitation,simple_daily_intensity_index,95_th_percentile_precipitation,99_th_percentile_precipitation,maximum_consecutive_wet_days,freeze_thaw_cycles
0,SSP2-4.5,1971-2000,10th_PERCENTILE,7.2,-6.3,4.9,18.9,8.7,11.7,-2.5,9.4,24.0,12.8,2.7,-10.1,0.4,13.7,4.5,113.7,671.9,125.6,140.9,141.5,144.9,28.5,41.1,4.4,9.9,18.9,4.2,49.8
1,SSP2-4.5,1971-2000,MEDIAN,8.1,-4.1,6.5,19.9,9.9,12.5,-0.5,11.2,25.1,14.1,3.6,-7.7,1.9,14.6,5.6,129.8,795.1,171.3,199.0,204.0,207.6,37.4,55.2,5.1,11.9,22.8,5.4,61.9
2,SSP2-4.5,1971-2000,90th_PERCENTILE,9.0,-1.9,8.2,21.0,11.2,13.5,1.5,13.2,26.5,15.5,4.6,-5.2,3.4,15.6,6.9,145.1,919.3,227.0,265.3,277.5,286.4,60.8,80.6,5.7,13.8,27.7,7.1,74.5
3,SSP2-4.5,2015-2040,10th_PERCENTILE,9.1,-3.8,6.8,20.6,10.5,13.4,-0.4,11.3,25.7,14.6,4.7,-7.3,2.2,15.4,6.2,87.5,700.6,139.6,149.2,140.4,148.8,29.4,42.9,4.6,10.4,19.7,4.4,41.9
4,SSP2-4.5,2015-2040,MEDIAN,10.1,-1.7,8.4,21.7,11.8,14.5,1.5,13.2,27.1,16.1,5.6,-5.0,3.7,16.3,7.4,106.5,832.8,188.0,212.1,208.7,213.1,40.4,58.2,5.3,12.3,24.1,5.6,54.5
5,SSP2-4.5,2015-2040,90th_PERCENTILE,11.2,0.3,10.2,23.0,13.3,15.7,3.3,15.2,28.7,18.0,6.7,-2.7,5.2,17.4,8.9,124.9,989.5,256.0,282.9,293.9,294.8,63.0,86.7,6.2,14.8,29.6,7.6,68.1
6,SSP2-4.5,2041-2070,10th_PERCENTILE,10.1,-2.7,7.8,21.5,11.4,14.4,0.6,12.2,26.6,15.6,5.7,-6.0,3.3,16.3,7.1,68.5,733.9,140.5,158.9,138.3,152.1,31.8,46.6,4.8,10.7,20.8,4.4,35.0
7,SSP2-4.5,2041-2070,MEDIAN,11.3,-0.4,9.5,22.9,12.8,15.7,2.6,14.3,28.3,17.2,6.8,-3.3,4.7,17.4,8.4,92.3,871.5,198.9,224.5,212.0,225.3,42.4,62.4,5.5,12.9,25.2,5.6,49.5
8,SSP2-4.5,2041-2070,90th_PERCENTILE,12.5,1.7,11.2,24.4,14.5,17.0,4.6,16.3,30.2,19.1,8.0,-1.1,6.1,18.7,10.1,113.1,1021.9,268.0,298.5,301.9,306.9,67.8,92.2,6.3,15.5,31.2,7.6,63.7
9,SSP2-4.5,2071-2100,10th_PERCENTILE,10.9,-1.5,8.5,22.2,12.1,15.2,1.6,13.0,27.4,16.3,6.6,-4.7,4.0,17.0,7.8,47.9,737.4,146.9,158.0,140.0,150.9,32.6,47.3,4.9,10.8,21.3,4.4,26.5
10,SSP2-4.5,2071-2100,MEDIAN,12.1,0.9,10.4,23.8,13.7,16.6,3.8,15.1,29.2,18.0,7.7,-2.0,5.5,18.3,9.3,79.7,885.4,208.8,230.7,207.9,220.0,44.1,63.5,5.6,13.2,25.7,5.7,44.9
11,SSP2-4.5,2071-2100,90th_PERCENTILE,13.8,3.3,12.2,25.7,15.7,18.4,6.0,17.3,31.6,20.4,9.3,0.6,7.2,19.8,11.2,102.8,1041.3,275.3,309.4,299.1,313.6,70.2,95.4,6.5,15.7,32.2,7.6,60.1
12,SSP5-8.5,1971-2000,10th_PERCENTILE,7.2,-6.3,4.9,18.9,8.7,11.7,-2.5,9.4,24.0,12.8,2.7,-10.1,0.4,13.7,4.5,113.7,671.9,125.6,140.9,141.5,144.9,28.5,41.1,4.4,9.9,18.9,4.2,49.8
13,SSP5-8.5,1971-2000,MEDIAN,8.1,-4.1,6.5,19.9,9.9,12.5,-0.5,11.2,25.1,14.1,3.6,-7.7,1.9,14.6,5.6,129.8,795.1,171.3,199.0,204.0,207.6,37.4,55.2,5.1,11.9,22.8,5.4,61.9
14,SSP5-8.5,1971-2000,90th_PERCENTILE,9.0,-1.9,8.2,21.0,11.2,13.5,1.5,13.2,26.5,15.5,4.6,-5.2,3.4,15.6,6.9,145.1,919.3,227.0,265.3,277.5,286.4,60.8,80.6,5.7,13.8,27.7,7.1,74.5
15,SSP5-8.5,2015-2040,10th_PERCENTILE,9.1,-3.8,6.5,20.6,10.5,13.4,-0.4,11.0,25.7,14.6,4.7,-7.3,2.1,15.4,6.2,84.9,712.7,137.2,150.0,139.8,148.3,30.1,44.4,4.6,10.4,20.1,4.3,41.9
16,SSP5-8.5,2015-2040,MEDIAN,10.2,-1.4,8.4,21.7,11.8,14.6,1.8,13.1,27.1,16.1,5.8,-4.7,3.7,16.4,7.5,104.8,840.4,191.2,211.0,211.1,212.4,41.4,59.5,5.3,12.4,24.4,5.7,54.6
17,SSP5-8.5,2015-2040,90th_PERCENTILE,11.4,0.8,10.1,23.3,13.3,16.0,3.8,15.3,28.9,17.8,6.9,-2.2,5.1,17.7,8.9,122.6,988.3,276.3,290.3,296.5,303.8,65.0,87.9,6.1,14.8,30.3,7.5,67.4
18,SSP5-8.5,2041-2070,10th_PERCENTILE,10.9,-1.6,8.5,22.2,12.0,15.2,1.5,13.0,27.3,16.2,6.6,-4.8,3.9,17.0,7.8,47.1,730.6,148.1,161.3,138.1,150.9,31.9,47.0,4.9,10.8,20.9,4.3,23.8
19,SSP5-8.5,2041-2070,MEDIAN,12.1,0.7,10.3,23.6,13.6,16.5,3.5,15.1,29.0,18.0,7.7,-2.2,5.5,18.2,9.2,80.5,874.9,203.5,229.1,208.1,223.6,43.9,64.1,5.6,13.1,25.7,5.7,44.4
20,SSP5-8.5,2041-2070,90th_PERCENTILE,13.7,3.3,12.0,25.6,15.6,18.2,6.0,17.1,31.7,20.3,9.2,0.7,7.0,19.7,11.2,102.4,1041.9,274.3,312.6,301.5,308.5,69.0,94.8,6.4,15.7,31.8,7.7,59.1
21,SSP5-8.5,2071-2100,10th_PERCENTILE,13.0,0.8,10.7,24.1,14.1,17.2,3.6,15.1,29.2,18.3,8.7,-2.2,6.1,18.9,9.8,11.6,775.1,165.2,171.8,131.5,155.3,33.9,50.6,5.1,11.5,22.3,4.4,5.3
22,SSP5-8.5,2071-2100,MEDIAN,14.6,3.2,12.5,26.4,16.2,18.9,5.9,17.4,31.8,20.6,10.2,0.5,7.7,20.9,11.7,47.5,921.4,224.5,243.8,205.5,229.8,47.5,69.4,5.9,13.9,27.4,5.8,29.3
23,SSP5-8.5,2071-2100,90th_PERCENTILE,16.8,5.8,14.7,29.0,19.1,21.3,8.2,19.8,35.2,23.8,12.4,3.6,9.8,22.9,14.6,77.4,1101.0,303.9,336.2,297.4,329.6,74.1,104.1,6.8,16.8,34.2,7.8,48.5