## Goals
This module seeks to split the complex dataset of ward-profiles, which contains several workbooks within the excel file.
Additionally, due to the vast amount of census data collected, each category would need to be split into it's own dataset as well.

In [1]:
import sys
from pathlib import Path
import pandas as pd

# add src to path
sys.path.append(str(Path.cwd().parents[1] / "src"))

from utils.data_loader import pull_data
from utils.data_loader import read_files

In [2]:
ROOT = Path.cwd().parents[1]   # project/
DATA_PATH = ROOT / "data/RawData/ward-profiles-25-ward-model"

In [3]:
EXCLUDED_WARD_FILES = {
   "2023-wardprofiles-geographicareas.xlsx",
}

In [4]:
def load_target_workbook_sheets(folder_path, target_stem, excluded_files=None):
    folder_path = Path(folder_path)
    excluded_files = excluded_files or set()

    for file_path in folder_path.glob("*.xls*"):
        if file_path.name in excluded_files:
            continue

        if file_path.stem.lower() == target_stem.lower():
            xls = pd.ExcelFile(file_path)

            return {
                sheet.lower().replace(" ", "_"): pd.read_excel(file_path, sheet_name=sheet)
                for sheet in xls.sheet_names
            }

    raise FileNotFoundError(f"{target_stem} not found in {folder_path}")

In [25]:
ward_profile_sheets = load_target_workbook_sheets(
    DATA_PATH,
    "2023-wardprofiles-2011-2021-censusdata_rev0719_modified",
    excluded_files=EXCLUDED_WARD_FILES
)

In [26]:
ward_profile_sheets.keys()

dict_keys(['2021population', '2021dwellings', '2021families', '2021education', '2021ethnic', '2021income', '2016population', '2016dwellings', '2016families', '2016education', '2016enthic', '2016labour', '2016income', '2011households', '2011families', '2011population'])

In [17]:
ward_names_file = DATA_PATH / "25-wardnames-numbers.xlsx"

ward_names = pull_data(files=[ward_names_file])["25-wardnames-numbers"]

In [16]:
ward_names

    Ward Number                 Ward Name
0             1           Etobicoke North
1             2          Etobicoke Centre
2             3       Etobicoke-Lakeshore
3             4        Parkdale-High Park
4             5         York South-Weston
5             6               York Centre
6             7  Humber River-Black Creek
7             8         Eglinton-Lawrence
8             9                 Davenport
9            10         Spadina-Fort York
10           11       University-Rosedale
11           12        Toronto-St. Paul’s
12           13            Toronto Centre
13           14          Toronto-Danforth
14           15           Don Valley West
15           16           Don Valley East
16           17          Don Valley North
17           18                Willowdale
18           19         Beaches-East York
19           20     Scarborough Southwest
20           21        Scarborough Centre
21           22     Scarborough-Agincourt
22           23         Scarborough North
23           24     Scarborough-Guildwood
24           25    Scarborough-Rouge Park

In [19]:
ward_profile_sheets['2021_one_variable']

,City of Toronto Profiles,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,City of Toronto: City Wards,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021 Census,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Source:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Statistics Canada, 2021 Census, Custom Tabulat...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,Canada Pension Plan (CPP) and QuÚbec Pensi...,3.5,5.2,3.7,2.8,2.5,5.1,4.5,5.8,2.7,...,4.7,4.3,3.6,2.8,4.2,5.3,7.2,7.1,5.5,4.9
1477,Old Age Security pension (OAS) and Guarant...,2.9,3.8,4.2,3,2.3,4,3.4,3.6,2.8,...,4,3.5,2.6,2.8,3.5,4.1,4.3,3.5,3.9,4.2
1478,Employment Insurance (EI) benefits %,1.3,2.1,1.1,1.3,1.2,2.2,1.8,2.5,1,...,1.4,1.3,1.1,1.3,1.8,1.9,1.7,1.9,1.8,1.7
1479,Child benefits $,2.8,6.9,2.2,1.6,1.4,5.4,3.7,7.8,1.8,...,4.2,2.8,2.1,2.4,5,5.7,4.3,5.8,6.6,4.2
1480,Other government transfers %,9.5,16.8,7.5,7.1,7.2,15.9,12.4,20,6.7,...,11.2,10.2,9.3,7.8,13,14.5,13.6,15.7,15.6,11.6